version: 0.2
phases:
  install:
    commands:
      - pwd
      - ls
      - sudo yum install mysql-devel
      - sudo pip-3.6 install mysql-connector
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket brigade-hqu-alpha-2 --output-template-file outputSamTemplate.yaml
                                  
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
