AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Functions for the HQU Backend
Resources:
  GetQuizScoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get_quiz_score.handler
      Runtime: python3.6
      CodeUri: ./
      Policies: AmazonDynamoDBReadOnlyAccess
      Events:
        GetQuizScore:
          Type: Api
          Properties:
            Path: /GetQuizScore
            Method: GET
  SaveQuestionResponseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: save_question_response.handler
      Runtime: python3.6
      CodeUri: ./
      Policies: AmazonDynamoDBFullAccess
      Events:
        SaveQuestionResponse:
          Type: Api
          Properties:
            Path: /SaveQuestionResponse
            Method: GET
  StartNewQuizFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: start_new_quiz.handler
      Runtime: python3.6
      CodeUri: ./
      Policies: AmazonDynamoDBFullAccess
      Events:
        StartNewQuiz:
          Type: Api
          Properties:
            Path: /StartNewQuiz
            Method: GET
